//
//  GistListPresenter.m
//  clean-swift-live
//
//  Created by Denis Kharitonov on 04.02.16.
//  Copyright (c) 2016 dk. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

#import "GistListPresenter.h"

@interface GistListPresenter ()
@end

@implementation GistListPresenter

#pragma mark - Presentation logic

- (void)presentSomething:(GistListResponse *)response
{
  // NOTE: Format the response from the Interactor and pass the result back to the View Controller
  
  GistListViewModel *viewModel = [[GistListViewModel alloc] init];
  [self.output displaySomething:viewModel];
}

-(void) presentListGists
{
    
}
@end
