//
//  GistListViewController.h
//  clean-swift-live
//
//  Created by Denis Kharitonov on 04.02.16.
//  Copyright (c) 2016 dk. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

#import "GistListCommon.h"

@class GistListRouter;

@interface GistListViewController: UIViewController <GistListViewControllerInput, GistListPresenterOutput>
@property (strong, nonatomic) id<GistListViewControllerOutput> output;
@property (strong, nonatomic) GistListRouter *router;
- (void)displaySomething:(GistListViewModel *)viewModel;
-(void) displayListGists;
@end
