//
//  GistListViewController.m
//  clean-swift-live
//
//  Created by Denis Kharitonov on 04.02.16.
//  Copyright (c) 2016 dk. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

#import "GistListViewController.h"

@interface GistListViewController ()
@end

@implementation GistListViewController

#pragma mark - Object lifecycle

- (void)awakeFromNib
{
  [super awakeFromNib];
  [[GistListConfigurator sharedInstance] configure:self];
}

#pragma mark - View lifecycle

- (void)viewDidLoad
{
    [super viewDidLoad];
    [self doSomethingOnLoad];
    [self listGistOnLoad];
}

#pragma mark - Event handling

- (void)doSomethingOnLoad
{
  // NOTE: Ask the Interactor to do some work
  
  GistListRequest *request = [[GistListRequest alloc] init];
  [self.output doSomething:request];
}

#pragma mark - Display logic

- (void)displaySomething:(GistListViewModel *)viewModel
{
  // NOTE: Display the result from the Presenter
  
  // self.nameTextField.text = viewModel.name;
}

#pragma mark - 
-(void) listGistOnLoad
{
    
}

-(void) displayListGists
{
    
}
@end
