//
//  GistListConfigurator.m
//  clean-swift-live
//
//  Created by Denis Kharitonov on 04.02.16.
//  Copyright (c) 2016 dk. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

#import "GistListConfigurator.h"

@interface GistListConfigurator ()
@end

@implementation GistListConfigurator

#pragma mark - Object lifecycle

+ (instancetype)sharedInstance
{
  static dispatch_once_t predicate;
  static GistListConfigurator *instance = nil;
  dispatch_once(&predicate, ^{instance = [[self alloc] init];});
  return instance;
}

#pragma mark - Configuration

- (void)configure:(GistListViewController *)viewController
{
  GistListRouter *router = [[GistListRouter alloc] init];
  router.viewController = viewController;
  
  GistListPresenter *presenter = [[GistListPresenter alloc] init];
  presenter.output = viewController;
  
  GistListInteractor *interactor = [[GistListInteractor alloc] init];
  interactor.output = presenter;
  
  viewController.output = interactor;
  viewController.router = router;
}

@end
